<a href="https://colab.research.google.com/github/tobiolad/python-codes/blob/main/Copy_of_analyst_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

&nbsp;
## Welcome to the Zippin Data Exploration!

Please analyze some actual anonymized Zippin transaction data using both Python and SQL (MySQL 5.7*).
<br><br>
A. Please address one or both of these prompts:

  1. **Store operator:** You are a Zippin analyst assigned to a new Zippin store (one of the two included in the data below).  Analyze the data and use one or two metrics that wouldn't be available for a traditional retail store to show the store operator how well the store is performing.


  2. **Investor:** You are a Zippin analyst presenting to a potential investor.  Analyze the data and present a metric that could help persuade your audience that  Zippin is a good investment.

B. Please analyze **data** and present one or more summaries of data (metrics) to answer these questions.  Please do not just describe what *could* be learned with an analysis but do the actual analysis and present data.
<br><br>
C. Please do this in **one sitting** and spend no more than 2 hours.  Please make the data clear and easy to digest, but no need for it to be polished or use graphs.
<br><br>
D. Please write answers/conclusions **just below** this instruction section.  This will make it easier to look for the supporting data.<br>
<br>--------------------<br>
\* *Note: MySQL 5.7 does not support windowing functions or CTE*<br>
&nbsp;



In total 678 customers visited the two stores in the month of may

Store 1 had 243 customers in the month of may

Store 2 had 435 customers in the month of may

We have just one tenant in Store 1 and one tenant in Store 2.

We have 320 unique items in store 2

We have 320 unique items in store 1





In [39]:
# Install any libraries you need.  In the example below we use pymysql.
# You can install most Python libraries in this way:
!pip install mysql-connector-python

In [40]:
# If you get a connection error below then please run this and email aaron@getzippin.com with the IP address of this instance of Colab so it can be whitelisted. 
!curl ipecho.net/plain

35.199.166.135

In [41]:


import mysql.connector

mydb = mysql.connector.connect(host='mysql.server307.com', 
                               port=3306, 
                               user='analyst', 
                               passwd='z1pp1nExcel', db='marsaxe_analyst')




In [42]:
mycursor = mydb.cursor()

mycursor.execute("SHOW TABLES")

for x in mycursor:
  print(x)

('Cart_Items',)
('Carts',)
('Categories',)
('SkuCategoriesMap',)
('Skus',)
('Stores',)
('Tenants',)


In [43]:
import mysql.connector

mydb = mysql.connector.connect(host='mysql.server307.com', 
                               port=3306, 
                               user='analyst', 
                               passwd='z1pp1nExcel', db='marsaxe_analyst')


mycursor = mydb.cursor()

try:
    mycursor.execute("SELECT * FROM Categories")
    result = mycursor.fetchall()
    num_fields = len(mycursor.description)
    field_names = [i[0] for i in mycursor.description]
    print(field_names)

    for value in result:
        print(value)

    mydb.commit()
except:
    mydb.rollback()
mydb.close()
result = mycursor.fetchall()
num_fields = len(mycursor.description)
field_names = [i[0] for i in mycursor.description]
print(field_names)
myresult = mycursor.fetchall()



['id', 'display_order', 'code', 'name', 'tenant_id', 'is_default']
(77, 1, 'lunch', 'Meals', '1122', 0)
(78, 2, 'drinks', 'Drinks', '1122', 0)
(79, 3, 'snacks', 'Snacks', '1122', 0)
(80, 4, 'miscellaneous', 'Miscellaneous', '1122', 1)
(81, 1, 'nonalcbev', 'Non-Alcoholic Beverages', '1121', 0)
(82, 2, 'alcbev', 'Alcoholic Beverages', '1121', 0)
(83, 3, 'snacks', 'Snacks', '1121', 0)
(84, 4, 'miscellaneous', 'Miscellaneous', '1121', 1)
(85, 5, 'bottledwater', 'Bottled Water', '1121', 0)
['id', 'display_order', 'code', 'name', 'tenant_id', 'is_default']


In [44]:
import mysql.connector

mydb = mysql.connector.connect(host='mysql.server307.com', 
                               port=3306, 
                               user='analyst', 
                               passwd='z1pp1nExcel', db='marsaxe_analyst')


mycursor = mydb.cursor()

try:
    mycursor.execute("SELECT * FROM Stores")
    result = mycursor.fetchall()
    num_fields = len(mycursor.description)
    field_names = [i[0] for i in mycursor.description]
    print(field_names)

    for value in result:
        print(value)

    mydb.commit()
except:
    mydb.rollback()
mydb.close()
result = mycursor.fetchall()
num_fields = len(mycursor.description)
field_names = [i[0] for i in mycursor.description]
print(field_names)
myresult = mycursor.fetchall()



['id', 'tenant_id', 'name']
('store1', '1121', 'NBA/NFL/MLB arena')
('store2', '1122', 'Hotel store')
['id', 'tenant_id', 'name']


We have just one tenant in Store 1 and one tenant in Store 2.



In [45]:
import mysql.connector

mydb = mysql.connector.connect(host='mysql.server307.com', 
                               port=3306, 
                               user='analyst', 
                               passwd='z1pp1nExcel', db='marsaxe_analyst')


mycursor = mydb.cursor()

try:
    mycursor.execute("SELECT * FROM Carts")
    result = mycursor.fetchall()
    num_fields = len(mycursor.description)
    field_names = [i[0] for i in mycursor.description]
    print(field_names)

    for value in result:
        print(value)

    mydb.commit()
except:
    mydb.rollback()
mydb.close()
result = mycursor.fetchall()
num_fields = len(mycursor.description)
field_names = [i[0] for i in mycursor.description]
print(field_names)
myresult = mycursor.fetchall()



['customer_id', 'cart_id', 'store_id', 'entry_time', 'exit_time', 'status', 'items', 'total_items', 'cart_type']
('8cbfc3fee153dd04706cc04d5dadaebe', '0058fb7870971ce0f70cb0c1f95db88e', 'store1', datetime.datetime(2021, 5, 3, 1, 21, 46), datetime.datetime(2021, 5, 3, 1, 22, 7), 'resolved', '[{"sku": "2008", "quantity": 2}]', 2, 'shopper')
('0e1c6ebdac22b18cf9f2fbf0a9d39f32', '0064031e795ea7bad5794c765bca8d73', 'store2', datetime.datetime(2021, 5, 10, 23, 39, 23), datetime.datetime(2021, 5, 10, 23, 55, 11), 'new', '[{"sku": "9014560272819145", "quantity": 0}, {"sku": "9014514410177147", "quantity": 0}, {"sku": "9014902831712533", "quantity": 0}, {"sku": "9014514410177116", "quantity": 0}, {"sku": "9014909411080891", "quantity": -1}, {"sku": "9014897036690017", "quantity": 1}, {"sku": "9014902888218835", "quantity": 0}, {"sku": "9014969244506654", "quantity": 0}, {"sku": "9014909411076634", "quantity": 0}, {"sku": "9014969244506647", "quantity": 0}, {"sku": "9014902102108065", "quantity"

In [46]:
import mysql.connector

mydb = mysql.connector.connect(host='mysql.server307.com', 
                               port=3306, 
                               user='analyst', 
                               passwd='z1pp1nExcel', db='marsaxe_analyst')


mycursor = mydb.cursor()

mycursor.execute("SELECT count(distinct customer_id) FROM Carts")

myresult = mycursor.fetchall()

for x in myresult:
  print(x)

(678,)


In total 678 customers visited the two stores in the month of may

In [47]:
import mysql.connector

mydb = mysql.connector.connect(host='mysql.server307.com', 
                               port=3306, 
                               user='analyst', 
                               passwd='z1pp1nExcel', db='marsaxe_analyst')


mycursor = mydb.cursor()

mycursor.execute("SELECT count(distinct customer_id) FROM Carts where store_id= 'store2'")

myresult = mycursor.fetchall()

for x in myresult:
  print(x)

(435,)


Store 2 had 435 customers in the month of may

In [52]:
import mysql.connector

mydb = mysql.connector.connect(host='mysql.server307.com', 
                               port=3306, 
                               user='analyst', 
                               passwd='z1pp1nExcel', db='marsaxe_analyst')


mycursor = mydb.cursor()

mycursor.execute("SELECT count(distinct customer_id) FROM Carts where store_id= 'store1'")

myresult = mycursor.fetchall()

for x in myresult:
  print(x)

(243,)


Store 1 had 243 customers in the month of may


In [56]:
import mysql.connector

mydb = mysql.connector.connect(host='mysql.server307.com', 
                               port=3306, 
                               user='analyst', 
                               passwd='z1pp1nExcel', db='marsaxe_analyst')


mycursor = mydb.cursor()

try:
    mycursor.execute("SELECT * FROM Skus")
    result = mycursor.fetchall()
    num_fields = len(mycursor.description)
    field_names = [i[0] for i in mycursor.description]
    print(field_names)

    for value in result:
        print(value)

    mydb.commit()
except:
    mydb.rollback()
mydb.close()
result = mycursor.fetchall()
num_fields = len(mycursor.description)
field_names = [i[0] for i in mycursor.description]
print(field_names)
myresult = mycursor.fetchall()



['id', 'tenant_id', 'tenant_sku_id', 'unit_weight', 'name', 'images', 'archived', 'created', 'updated']
(130004, '1122', '90149795615', 106, "NONIO mouse W Non'aru L Ha", '[{"url": "https://storage.googleapis.com/zyp-store.appspot.com/thumbnails/1121/90149795615.jpg"}]', 0, datetime.datetime(2020, 12, 24, 10, 0, 21), datetime.datetime(2021, 5, 13, 1, 27, 18))
(130005, '1122', '9012300230104027', 452, 'Ginger grilled lunch of pork', '[{"url": "https://storage.googleapis.com/zyp-store.appspot.com/thumbnails/1121/9012300230104027.jpg"}]', 0, datetime.datetime(2020, 12, 24, 10, 0, 25), datetime.datetime(2021, 5, 13, 1, 26, 30))
(130012, '1122', '9012399930012367', 416, 'Dry curry', '[{"url": "https://storage.googleapis.com/zyp-store.appspot.com/thumbnails/1121/9012399930012367.jpg"}]', 0, datetime.datetime(2020, 12, 24, 10, 0, 54), datetime.datetime(2021, 5, 13, 1, 26, 31))
(130015, '1122', '90149810462', 65, 'Milk caramel N 12 tablets', '[{"url": "https://storage.googleapis.com/zyp-store.

In [59]:
import mysql.connector

mydb = mysql.connector.connect(host='mysql.server307.com', 
                               port=3306, 
                               user='analyst', 
                               passwd='z1pp1nExcel', db='marsaxe_analyst')


mycursor = mydb.cursor()

mycursor.execute("SELECT count(distinct name) FROM Skus")

myresult = mycursor.fetchall()

for x in myresult:
  print(x)

(358,)


In [ ]:
We have 358 unique items in total from the two stores

In [60]:
import mysql.connector

mydb = mysql.connector.connect(host='mysql.server307.com', 
                               port=3306, 
                               user='analyst', 
                               passwd='z1pp1nExcel', db='marsaxe_analyst')


mycursor = mydb.cursor()

mycursor.execute("SELECT count(distinct name) FROM Skus where tenant_id = 1122 ")

myresult = mycursor.fetchall()

for x in myresult:
  print(x)

(320,)


We have 320 unique items in store 2

In [61]:
import mysql.connector

mydb = mysql.connector.connect(host='mysql.server307.com', 
                               port=3306, 
                               user='analyst', 
                               passwd='z1pp1nExcel', db='marsaxe_analyst')


mycursor = mydb.cursor()

mycursor.execute("SELECT count(distinct name) FROM Skus where tenant_id = 1121 ")

myresult = mycursor.fetchall()

for x in myresult:
  print(x)

(38,)


We have 38 unique items in store 1
